repository_type: pipeline

nf_core_version: 3.4.1

lint: {}

template:
  org: nf-core
  name: atacCo
  description: ATAC related analyses
  author: YuanLi
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
